name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: job1
        uses: actions/checkout@v3
      - run: echo "Version of Python is" python --version "."
  job2:
    runs-on: ubuntu-latest
    steps:
        - name: job2
          uses: actions/checkout@v3
        - run: |
            python -m pip install --upgrade pip
            pip install pylint
        - run: |
            find . -name '*.py' -exec pylint {} \;
        
 
      
