name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: job1
      - run: echo "Version of Pyton is ${{ python --version }}.
  job2:
    runs-on: ubuntu-latest
    steps:
        - name: job2
          uses: actions/checkout@v3
        - run: pyton -m pip install --upgrade pip
             pip install pylint
        - run: |
            find . -name 'app.py' -exec pylint {} \;
        
 
      
