name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps: 
        - run: echo "Version of Pyton is ${{ python.version }}.
  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - run: pyton -m pip install
             pip install pylint
      - run: |
          find . -name 'app.py' -exec pylint {} \;
        
 
      
